spring:
  application:
    name: card_payment_processor
  cassandra:
    contact-points: localhost:9042
    keyspace-name: payment_processor
    local-datacenter: datacenter1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
